Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.9"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
  end
  config.vm.provision "shell", reboot: false, path: "../Script/base.sh"
  config.vm.provision "shell", reboot: false, path: "../Script/repos.sh"
  config.vm.provision "shell", reboot: false, path: "../Script/docker.sh"
  config.vm.provision "shell", reboot: true, inline: <<-SHELL
  SHELL
  (1..1).each do |i|
    config.vm.define "host-#{i}" do |host|
      host.vm.hostname = "host-#{i}"
      host.vm.network "private_network", ip: "192.168.56.1#{i}"
    end
  end
end
